export const MEDICINE_FIELDS = [
    {
        label: "Dosage Quantiy",
        operator: "input",
        name: "dosageQuantity",
        value: "",
    },
    {
        label: "Dosage Type",
        operator: "radio",
        name: "dosageType",
        value: "meals",
        possible_values: ["meals", "frequency", "timings"],
    },
    {
        label: "Frequency Type",
        operator: "radio",
        name: "frequencyMealType",
        value: "After Meal",
        possible_values: ["Before Meal", "After Meal"],
    },
    {
        label: "Meals Breakfast",
        operator: "input",
        name: "mealsBreakFastBefore",
        value: "",
    },
    {
        label: "Meals Breakfast",
        operator: "input",
        name: "mealsBreakFastAfter",
        value: "",
    },
    {
        label: "Meals Lunch",
        operator: "input",
        name: "mealsLunchBefore",
        value: "",
    },
    {
        label: "Meals Lunch",
        operator: "input",
        name: "mealsLunchAfter",
        value: "",
    },
    {
        label: "Meals Dinner",
        operator: "input",
        name: "mealsDinnerBefore",
        value: "",
    },
    {
        label: "Meals Dinner",
        operator: "input",
        name: "mealsDinnerAfter",
        value: "",
    },
    {
        label: "Meals",
        operator: "checkbox",
        name: "meals",
        value: [],
        possible_values: ["breakfast", "lunch", "dinner"],
    },
    {
        label: "Frequency",
        operator: "radio",
        name: "frequency",
        value: "",
        possible_values: ["2", "4", "6", "8", "12", "24", "custom"],
    },
    {
        label: "customFrequencyValue",
        operator: "input",
        name: "customFrequencyValue",
        value: "",
    },
    {
        label: "customFrequency",
        operator: "select",
        name: "customFrequency",
        value: "",
        possible_values: ["Please Select", "hours", "days", "weeks", "months"],
    },
    {
        label: "Timings",
        operator: "checkbox",
        name: "timings",
        value: [],
        possible_values: ["morning", "afternoon", "evening", "night", "midnight"],
    },
    {
        label: "Timings Morning",
        operator: "input",
        name: "timingsMorningBefore",
        value: "",
    },
    {
        label: "Timings Morning",
        operator: "input",
        name: "timingsMorningAfter",
        value: "",
    },
    {
        label: "Timings Afternoon",
        operator: "input",
        name: "timingsAfternoonBefore",
        value: "",
    },
    {
        label: "Timings Afternoon",
        operator: "input",
        name: "timingsAfternoonAfter",
        value: "",
    },
    {
        label: "Timings Night",
        operator: "input",
        name: "timingsNightBefore",
        value: "",
    },
    {
        label: "Timings Night",
        operator: "input",
        name: "timingsNightAfter",
        value: "",
    },
    {
        label: "Days",
        operator: "select",
        name: "days",
        value: "daily",
        possible_values: ["daily", "alternate", "required"],
    },
    {
        label: "Duration",
        operator: "select",
        name: "duration",
        value: "1d",
        text_values: [
            "1 day",
            "2 days",
            "3 days",
            "4 days",
            "5 days",
            "6 days",
            "7 days",
            "2 weeks",
            "3 weeks",
            "4 weeks",
            "2 months",
            "3 months",
            "4 months",
        ],
        possible_values: ["1d", "2d", "3d", "4d", "5d", "6d", "7d", "2w", "3w", "4w", "2m", "3m", "4m"],
    },
    {
        label: "Number",
        operator: "input",
        name: "number",
        value: "",
    },
    {
        label: "Others",
        operator: "radio",
        name: "others",
        value: "",
        possible_values: ["before", "after", "empty"],
    },
];
