export const REGEX = {
    VALID_EMAIL_REGEX: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
};

export const TIME_FORMAT = "h:mm a";
export const WEEK_DAYS = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"];
export const REVERSE_WEEK_DAYS = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"];

export const SIDEBAR_VISIBLE_ROUTES = ["/home"];

export const MEDICINE_FORMS = [
    "Please Select",
    "Tablet",
    "Syrup",
    "Drop",
    "Cream",
    "Capsule",
    "Injection",
    "Powder",
    "Sachet",
    "Lotion",
    "Gel",
    "Ointment",
    "Suspension",
    "Spray",
    "Soap",
    "Inhaler",
    "Liquid",
    "Respule",
    "Shampoo",
    "Suppository",
    "Solution",
    "Granule",
    "Oil",
    "Milk",
    "Rotacap",
    "Infusion",
    "Other",
    "Aplicap",
    "Bar",
    "Face Wash",
    "Lozenge",
    "Balm",
    "Vial",
    "Mouthwash",
    "Device",
    "Patch",
    "Serum",
    "Enema",
    "Mouth Paint",
    "Pessary",
    "Tube",
    "Expectorant",
    "Kit",
    "Biscuit",
    "Emulsion",
    "Jelly",
    "Paste",
    "Transpule",
    "Cartridge",
    "Hygiene",
    "Paint",
    "Elixir",
    "Spacer",
    "Pen",
    "Liniment",
    "Gum Paint",
    "Wash Kit",
    "Glue",
    "Conditioner",
    "Toothpaste",
    "Transcap",
    "Mask",
    "Shield",
    "Transhaler",
    "Gargle",
    "Linctus",
    "Gum Astringent",
    "Octacap",
    "Strip",
    "Nebuliser",
    "Vaccine",
    "Dressing",
    "Oral Solution",
    "Oral Vaccine",
    "Softule",
    "Aerosol",
    "Bead",
    "Block",
    "Catheter",
    "Cellular Sheet",
    "Cement",
    "Chewable Gel",
    "Cigarette",
    "Cloth",
    "Concentrate",
    "Cone",
    "Core",
    "Crystal",
    "Culture",
    "Diaphragm",
    "Disc",
    "Dosing",
    "Douche",
    "Extract",
    "Fiber",
    "Film",
    "Gas",
    "Generator",
    "Globule",
    "Graft",
    "Gum",
    "Implant",
    "Inhalant",
    "Injectable",
    "Injectable Foam",
    "Insert",
    "Intrauterine Device",
    "Irrigant",
    "Liner",
    "Lipstick",
    "Not Applicable",
    "Note",
    "Packing",
    "Pastille",
    "Pellet",
    "Pill",
    "Plaster",
    "Poultice",
    "Ring",
    "Rinse",
    "Salve",
    "Sponge",
    "Stick",
    "Suture",
    "Swab",
    "System",
    "Tampon",
    "Tape",
    "Tincture",
    "Troche",
    "Wafer",
];
